version: '3'
services:
    web:
        build: .
        ports:
            - '3000:3000'
            - '8080:8080'
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: localpass
            MYSQL_DATABASE: alarmmanager
            MYSQL_USER: admin
            MYSQL_PASSWORD: localpass
        ports:
            - '3306:3306'
